repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0  # Choose the latest stable version
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: v4.0.1  # Choose the latest stable version
    hooks:
      - id: flake8

